# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "03ccccfa9441364ec4ba652e625c647a"
name = "ENTD Store"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
automatically_update_urls_on_dev = true
